Se incluye framework de pruebas para EvolutionWave
sbarahonaQA/EvolutionTest pull request #42
Opened 2021-12-22 17:26 UTC by sbarahonaQA

iniciando con PDS-4356

2022-01-11 23:16 UTC, csoriaQA requested changes
Revisar los comentarios

2022-01-11 23:16 UTC, csoriaQA commented on src/test/resources/Pages/DEV/evowave/acciones/autorizadores_sustitutos/AutorizadoresSustitutos.json
> +    "ValueToFind": "//app-date[1]//mat-form-field[1]//div[1]//div[1]//div[4]//mat-datepicker-toggle[1]//button[1]"
```suggestion
    "ValueToFind": "(//form//button)[1]"
```

2022-01-11 23:16 UTC, csoriaQA commented on src/test/resources/Pages/DEV/evowave/acciones/autorizadores_sustitutos/AutorizadoresSustitutos.json
> +    "ValueToFind": "//app-date[2]//mat-form-field[1]//div[1]//div[1]//div[4]//mat-datepicker-toggle[1]//button[1]"
```suggestion
    "ValueToFind": "(//form//button)[2]"
```

2022-01-12 22:25 UTC, sbarahonaQA commented on src/test/java/Functions/SeleniumFunctionsEvoWave.java
> +public class SeleniumFunctionsEvoWave {
Leyendo la documentacion me di cuenta que pueden haber mande un archivo de functions, pero los nombres de los metodos no pueden repetirse asi que, por el momento, no aporta mucho tener mas de uno. Dejaré solamente un archivo

2022-01-12 22:25 UTC, sbarahonaQA commented on src/test/java/StepDefinitions/StepDefinitionsEvoWave.java
> +public class StepDefinitionsEvoWave {
Leyendo la documentacion me di cuenta que pueden haber mande un archivo de functions, pero los nombres de los metodos no pueden repetirse asi que, por el momento, no aporta mucho tener mas de uno. Dejaré solamente un archivo

2022-01-12 22:26 UTC, sbarahonaQA commented on src/test/resources/Features/DEV/evowave/acciones/autorizadores_sustitutos/AutorizadoresSustitutos.feature
> +  Escenario: Crear una solicitud de autorizador sustituto con información básica (formulario completo) (PDS-7036)
Hace falta ajustar las rutas json según los cambios de carpetas que se hicieron

2022-01-12 22:27 UTC, sbarahonaQA commented on src/test/resources/Features/DEV/evowave/acciones/autorizadores_sustitutos/AutorizadoresSustitutos.feature
> +    * Click a FechaInicio
Lo hice asi para que se pudiera ejecutar la prueba pero voy a crear un nuevo para para simplificar

2022-01-12 22:28 UTC, sbarahonaQA commented on src/test/resources/Features/DEV/evowave/consultas/incapacidades/Incapacidades.feature
> +    * Click a Desde
Lo hice asi para que se pudiera ejecutar la prueba pero voy a crear un nuevo para para simplificar

2022-01-12 22:29 UTC, sbarahonaQA commented on src/test/resources/Pages/DEV/evowave/Inicio.json
> +    "ValueToFind": "//div[1]//div[1]//a[1]//div[1]//span[1]"
Se cargarán los cambios sugeridos

2022-01-12 22:30 UTC, sbarahonaQA commented on src/test/resources/Pages/DEV/evowave/acciones/autorizadores_sustitutos/AutorizadoresSustitutos.json
> +    "ValueToFind": "//app-date[1]//mat-form-field[1]//div[1]//div[1]//div[4]//mat-datepicker-toggle[1]//button[1]"
Se cargarán los cambios sugeridos

2022-01-12 22:30 UTC, sbarahonaQA commented on src/test/resources/Pages/DEV/evowave/acciones/autorizadores_sustitutos/AutorizadoresSustitutos.json
> +    "ValueToFind": "//app-date[2]//mat-form-field[1]//div[1]//div[1]//div[4]//mat-datepicker-toggle[1]//button[1]"
Se cargarán los cambios sugeridos

2022-01-13 16:18 UTC, csoriaQA approved these changes

2022-01-13 16:25 UTC, merged